spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
#              cpu: "0.2"
#              memory: 256Mi
            limits:
#              cpu: "1.0"
#              memory: 512Mi
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-amq-tcp
          - name: JAVA_OPTIONS
            value: -XX:NativeMemoryTracking=summary -XX:MaxRAM=300m
